Repository munich-quantum-toolkit/problemsolver, pull requests merged in 2025-08, with the labels that each got.

#156 Fix function name and minor typo
  README.md
  notebooks/satellitesolver/satellitesolver_example.ipynb
  src/mqt/problemsolver/satellitesolver/utils.py
Labels: documentation

#159 Improve Version Conflict Handling Between qsharp and qiskit.
  resource_estimation/FT_Optimization/FT_optimization_evaluation.ipynb
  resource_estimation/FT_Optimization/FT_optimization_generate_data.py
Labels: dependencies, usability

#160 🚚 rename FT folder and files to follow naming convention
  resource_estimation/ft_optimization/evaluation.ipynb
  resource_estimation/ft_optimization/generate_data.py
  resource_estimation/ft_optimization/mqtbench/ae_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/dj_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/graphstate_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/grover-noancilla_indep_qiskit_7.qasm
  resource_estimation/ft_optimization/mqtbench/grover-v-chain_indep_qiskit_7.qasm
  resource_estimation/ft_optimization/mqtbench/qft_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/qftentangled_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/qpeexact_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/qpeinexact_indep_qiskit_10.qasm
  resource_estimation/ft_optimization/mqtbench/qwalk-noancilla_indep_qiskit_7.qasm
  resource_estimation/ft_optimization/mqtbench/qwalk-v-chain_indep_qiskit_5.qasm
  resource_estimation/ft_optimization/mqtbench/qwalk-v-chain_indep_qiskit_7.qasm
Labels: usability
